[theme]
base = "light"
primaryColor = "#004F9F"  # 중근당 BLUE
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
address = "0.0.0.0"  # 모든 네트워크 인터페이스에서 접근 허용
port = 80
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[browser]
# serverAddress = "192.168.142.68"  # 외부에서 접속할 때 사용할 IP 주소
# serverPort = 80